[package]
name = "fakeDrip"
version = "0.1.0"
edition = "2018"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true

[dependencies]
colored = "2.0"
terminal_size = "0.4.0"
sysinfo = "0.32.0"
ntapi = "0.4.1"
winapi = { version = "0.3", features = ["consoleapi", "winuser"] }
